// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD3hp89kop8iKcYvTbMDY1-QwO2CD0UWU',
    appId: '1:768349962577:web:b7c8a64f34d19d9db95370',
    messagingSenderId: '768349962577',
    projectId: 'shop-app-thinknext',
    authDomain: 'shop-app-thinknext.firebaseapp.com',
    storageBucket: 'shop-app-thinknext.appspot.com',
    measurementId: 'G-SVXDBYDJ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYD4sfDVN2d95SvH8aJFH_3oxnxafLoaM',
    appId: '1:768349962577:android:2cc7753a837e2909b95370',
    messagingSenderId: '768349962577',
    projectId: 'shop-app-thinknext',
    storageBucket: 'shop-app-thinknext.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_Wme-5dmz9oa_vnYNy9uABGooruBaJ0',
    appId: '1:768349962577:ios:cbdfa94810415165b95370',
    messagingSenderId: '768349962577',
    projectId: 'shop-app-thinknext',
    storageBucket: 'shop-app-thinknext.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_Wme-5dmz9oa_vnYNy9uABGooruBaJ0',
    appId: '1:768349962577:ios:cbdfa94810415165b95370',
    messagingSenderId: '768349962577',
    projectId: 'shop-app-thinknext',
    storageBucket: 'shop-app-thinknext.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD3hp89kop8iKcYvTbMDY1-QwO2CD0UWU',
    appId: '1:768349962577:web:201362a73d8fcae1b95370',
    messagingSenderId: '768349962577',
    projectId: 'shop-app-thinknext',
    authDomain: 'shop-app-thinknext.firebaseapp.com',
    storageBucket: 'shop-app-thinknext.appspot.com',
    measurementId: 'G-DRC9RH3F3F',
  );
}
